package mif.mybatis.dao;

import java.util.List;
import mif.mybatis.model.City;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int updateByPrimaryKey(City record);
}