package mif.mybatis.dao;

import mif.mybatis.model.Country;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COUNTRY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COUNTRY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COUNTRY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COUNTRY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COUNTRY
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    int updateByPrimaryKey(Country record);

    List<Country> selectNeighbours();
}