package mif.mybatis.dao;

import java.util.List;
import mif.mybatis.model.Neighbours;
import org.mybatis.cdi.Mapper;

@Mapper
public interface NeighboursMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NEIGHBOURS
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    int insert(Neighbours record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.NEIGHBOURS
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    List<Neighbours> selectAll();
}