package mif.mybatis.model;

public class City {
    private Country country;

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.IS_CAPITAL
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    private Boolean isCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.NAME
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    private Integer countryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.ID
     *
     * @return the value of PUBLIC.CITY.ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.ID
     *
     * @param id the value for PUBLIC.CITY.ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.IS_CAPITAL
     *
     * @return the value of PUBLIC.CITY.IS_CAPITAL
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public Boolean getIsCapital() {
        return isCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.IS_CAPITAL
     *
     * @param isCapital the value for PUBLIC.CITY.IS_CAPITAL
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public void setIsCapital(Boolean isCapital) {
        this.isCapital = isCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.NAME
     *
     * @return the value of PUBLIC.CITY.NAME
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.NAME
     *
     * @param name the value for PUBLIC.CITY.NAME
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.COUNTRY_ID
     *
     * @return the value of PUBLIC.CITY.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.COUNTRY_ID
     *
     * @param countryId the value for PUBLIC.CITY.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 27 15:21:20 EET 2021
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }
}