package mif.mybatis.model;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COUNTRY.ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COUNTRY.NAME
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COUNTRY.CAPITALCITY_ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    private Integer capitalcityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COUNTRY.ID
     *
     * @return the value of PUBLIC.COUNTRY.ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COUNTRY.ID
     *
     * @param id the value for PUBLIC.COUNTRY.ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COUNTRY.NAME
     *
     * @return the value of PUBLIC.COUNTRY.NAME
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COUNTRY.NAME
     *
     * @param name the value for PUBLIC.COUNTRY.NAME
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COUNTRY.CAPITALCITY_ID
     *
     * @return the value of PUBLIC.COUNTRY.CAPITALCITY_ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public Integer getCapitalcityId() {
        return capitalcityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COUNTRY.CAPITALCITY_ID
     *
     * @param capitalcityId the value for PUBLIC.COUNTRY.CAPITALCITY_ID
     *
     * @mbg.generated Wed Mar 24 18:25:49 EET 2021
     */
    public void setCapitalcityId(Integer capitalcityId) {
        this.capitalcityId = capitalcityId;
    }
}