package mif.mybatis.model;

public class Neighbours {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NEIGHBOURS.COUNTRY_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    private Integer countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.NEIGHBOURS.NEIGHBOURS_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    private Integer neighboursId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NEIGHBOURS.COUNTRY_ID
     *
     * @return the value of PUBLIC.NEIGHBOURS.COUNTRY_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NEIGHBOURS.COUNTRY_ID
     *
     * @param countryId the value for PUBLIC.NEIGHBOURS.COUNTRY_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.NEIGHBOURS.NEIGHBOURS_ID
     *
     * @return the value of PUBLIC.NEIGHBOURS.NEIGHBOURS_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    public Integer getNeighboursId() {
        return neighboursId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.NEIGHBOURS.NEIGHBOURS_ID
     *
     * @param neighboursId the value for PUBLIC.NEIGHBOURS.NEIGHBOURS_ID
     *
     * @mbg.generated Mon Mar 29 20:09:53 EEST 2021
     */
    public void setNeighboursId(Integer neighboursId) {
        this.neighboursId = neighboursId;
    }
}